services:
  wordpress:
    build: ./wordpress
    container_name: my_wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    ports:
      - "8080:80"
    networks:
      - my_network
  mariadb:
    build: ./mariadb
    container_name: my_maria
    env_file:
      - ./.env
    expose:
      - 3306
    volumes:
      - maria_db:/var/lib/mysql
    networks:
      - my_network

  nginx:
    build: ./nginx
    container_name: my_nginx
    depends_on:
      - wordpress
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 80:80
    networks:
      - my_network
volumes:
  maria_db:
  wp_data:

networks:
  my_network:
    driver: bridge