networks:
  my_network:
    driver: bridge

volumes:
  maria_db:
  wp_data:


services:
  wordpress:
    build: ./wordpress
    container_name: my_wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    ports:
      - "8080:9000"
    networks:
      - my_network
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${WORDPRESS_DB_NAME}
        DB_USER: ${WORDPRESS_DB_USER}
        DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    container_name: my_maria
    
    expose:
      - 3306
    volumes:
      - maria_db:/var/lib/mysql
      - ./mariadb/logs:/var/logs/mysql
    networks:
      - my_network

  nginx:
    build: ./nginx
    container_name: my_nginx
    env_file:
      - ./.env
    depends_on:
      - wordpress
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - my_network

