version: '3.5'

networks:
  my_network:
    driver: bridge

volumes:
  maria_db:
    driver: local
    name: volume_mariadb
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MARIADB}
  wp_data:
    driver: local
    name: volume_wordpress
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_WORDPRESS}


services:
  wordpress:
    build: ./requirements/wordpress
    container_name: my_wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    networks:
      - my_network
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${WORDPRESS_DB_NAME}
        DB_USER: ${WORDPRESS_DB_USER}
        DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    container_name: my_maria
    expose:
      - 3306
    volumes:
      - maria_db:/var/lib/mysql
      - ./requirements/mariadb/logs:/var/logs/mysql
    networks:
      - my_network

  nginx:
    build: ./requirements/nginx
    container_name: my_nginx
    env_file:
      - ./.env
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./requirements/nginx/logs:/var/log/nginx/
      - wp_data:/var/www/html
    ports:
      - 443:443
    networks:
      - my_network

